import { Deal } from "@/types/deal"

export const mockDeals: Deal[] = [
    {
        id: "DEA-001",
        title: "Downtown Loft Purchase",
        value: 450000,
        stage: "lead",
        customerName: "Alice Freeman",
        customerEmail: "alice@example.com",
        property: { id: "1", title: "Modern Downtown Apartment" },
        expectedCloseDate: new Date("2024-03-15"),
        priority: "high",
        agent: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-15"),
        updatedAt: new Date("2024-01-20"),
    },
    {
        id: "DEA-002",
        title: "Riverside Condo Investment",
        value: 850000,
        stage: "negotiation",
        customerName: "Robert Liu",
        customerEmail: "robert@tech.co",
        property: { id: "3", title: "Luxury Waterfront Condo" },
        expectedCloseDate: new Date("2024-02-28"),
        priority: "medium",
        agent: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-10"),
        updatedAt: new Date("2024-01-22"),
    },
    {
        id: "DEA-003",
        title: "Heritage Townhouse",
        value: 975000,
        stage: "under_contract",
        customerName: "Sarah Connor",
        customerEmail: "sarah@design.io",
        property: { id: "4", title: "Charming Historic Townhouse" },
        expectedCloseDate: new Date("2024-02-15"),
        priority: "high",
        agent: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2023-12-20"),
        updatedAt: new Date("2024-01-23"),
    },
    {
        id: "DEA-004",
        title: "Commercial Space Lease",
        value: 2500000,
        stage: "lead",
        customerName: "TechStart Inc",
        customerEmail: "founders@techstart.com",
        property: { id: "5", title: "Prime Commercial Space" },
        expectedCloseDate: new Date("2024-04-01"),
        priority: "low",
        agent: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-22"),
        updatedAt: new Date("2024-01-22"),
    },
    {
        id: "DEA-005",
        title: "Family Home Upgrade",
        value: 1200000,
        stage: "closed",
        customerName: "The Wilsons",
        customerEmail: "mike.wilson@corp.net",
        property: { id: "2", title: "Spacious Family Home" },
        expectedCloseDate: new Date("2024-01-15"),
        priority: "medium",
        agent: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2023-11-15"),
        updatedAt: new Date("2024-01-15"),
    },
    {
        id: "DEA-006",
        title: "Investment Portfolio",
        value: 320000,
        stage: "negotiation",
        customerName: "James Bond",
        customerEmail: "007@mi6.gov",
        property: { id: "1", title: "Modern Downtown Apartment" },
        expectedCloseDate: new Date("2024-03-01"),
        priority: "high",
        agent: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-18"),
        updatedAt: new Date("2024-01-21"),
    },
]
