import { Lead } from "@/types/lead"

export const mockLeads: Lead[] = [
    {
        id: "1",
        name: "Sarah Johnson",
        email: "sarah.j@email.com",
        phone: "+1 (555) 123-4567",
        status: "qualified",
        source: "website",
        budget: 450000,
        location: "Downtown, New York",
        propertyType: "Apartment",
        notes: "Looking for 2BR apartment, move-in by March",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-15"),
        lastContact: new Date("2024-01-20"),
    },
    {
        id: "2",
        name: "Michael Chen",
        email: "m.chen@techco.com",
        phone: "+1 (555) 234-5678",
        status: "contacted",
        source: "referral",
        budget: 850000,
        location: "Brooklyn, New York",
        propertyType: "House",
        notes: "Family of 4, needs 3-4 bedrooms with yard",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-18"),
        lastContact: new Date("2024-01-22"),
    },
    {
        id: "3",
        name: "Emily Rodriguez",
        email: "emily.r@gmail.com",
        phone: "+1 (555) 345-6789",
        status: "new",
        source: "social",
        budget: 320000,
        location: "Queens, New York",
        propertyType: "Condo",
        notes: "First-time buyer, needs financing guidance",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-25"),
    },
    {
        id: "4",
        name: "David Kim",
        email: "david.kim@startup.io",
        phone: "+1 (555) 456-7890",
        status: "qualified",
        source: "website",
        budget: 1200000,
        location: "Manhattan, New York",
        propertyType: "Commercial",
        notes: "Tech startup looking for office space, 3000+ sq ft",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-10"),
        lastContact: new Date("2024-01-24"),
    },
    {
        id: "5",
        name: "Lisa Anderson",
        email: "lisa.anderson@corp.com",
        phone: "+1 (555) 567-8901",
        status: "contacted",
        source: "cold_call",
        budget: 675000,
        location: "Jersey City, New Jersey",
        propertyType: "Townhouse",
        notes: "Relocating from California, flexible timeline",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-12"),
        lastContact: new Date("2024-01-19"),
    },
    {
        id: "6",
        name: "Robert Williams",
        email: "r.williams@email.com",
        phone: "+1 (555) 678-9012",
        status: "new",
        source: "event",
        budget: 520000,
        location: "Hoboken, New Jersey",
        propertyType: "Apartment",
        notes: "Met at real estate expo, interested in waterfront properties",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-26"),
    },
    {
        id: "7",
        name: "Jennifer Martinez",
        email: "jenn.m@design.co",
        phone: "+1 (555) 789-0123",
        status: "lost",
        source: "referral",
        budget: 420000,
        location: "Williamsburg, Brooklyn",
        propertyType: "Loft",
        notes: "Found property through another agent",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-08"),
        lastContact: new Date("2024-01-15"),
    },
    {
        id: "8",
        name: "James Taylor",
        email: "james.t@finance.com",
        phone: "+1 (555) 890-1234",
        status: "qualified",
        source: "website",
        budget: 950000,
        location: "Upper East Side, Manhattan",
        propertyType: "Apartment",
        notes: "Investment property, looking for rental income potential",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-14"),
        lastContact: new Date("2024-01-23"),
    },
]