import { Lead } from "@/types/lead"

export const mockLeads: Lead[] = [
    {
        id: "1",
        name: "Sarah Johnson",
        email: "sarah.j@email.com",
        phone: "+91 98765 43210",
        status: "qualified",
        source: "website",
        budgetMin: 4000000,
        budgetMax: 5000000,
        preferredLocation: "Powai, Mumbai",
        propertyType: "2 BHK",
        bedroom: 2,
        notes: "Looking for 2BR apartment, move-in by March",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-15"),
        lastContact: new Date("2024-01-20"),
    },
    {
        id: "2",
        name: "Michael Chen",
        email: "m.chen@techco.com",
        phone: "+91 98765 43211",
        status: "contacted",
        source: "referral",
        budgetMin: 8000000,
        budgetMax: 10000000,
        preferredLocation: "Brooklyn, New York",
        propertyType: "3 BHK",
        bedroom: 3,
        notes: "Family of 4, needs 3-4 bedrooms with yard",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-18"),
        lastContact: new Date("2024-01-22"),
    },
    {
        id: "3",
        name: "Emily Rodriguez",
        email: "emily.r@gmail.com",
        phone: "+91 98765 43212",
        status: "new",
        source: "social",
        budgetMin: 3000000,
        budgetMax: 4000000,
        preferredLocation: "Queens, New York",
        propertyType: "2 BHK",
        bedroom: 2,
        notes: "First-time buyer, needs financing guidance",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-25"),
    },
    {
        id: "4",
        name: "David Kim",
        email: "david.kim@startup.io",
        phone: "+91 98765 43213",
        status: "qualified",
        source: "99acres",
        budgetMin: 10000000,
        budgetMax: 15000000,
        preferredLocation: "Manhattan, New York",
        propertyType: "Penthouse",
        bedroom: 4,
        notes: "Tech startup looking for office space, 3000+ sq ft",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-10"),
        lastContact: new Date("2024-01-24"),
    },
    {
        id: "5",
        name: "Lisa Anderson",
        email: "lisa.anderson@corp.com",
        phone: "+91 98765 43214",
        status: "contacted",
        source: "cold_call",
        budgetMin: 6000000,
        budgetMax: 8000000,
        preferredLocation: "Jersey City, New Jersey",
        propertyType: "Row House",
        bedroom: 3,
        notes: "Relocating from California, flexible timeline",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-12"),
        lastContact: new Date("2024-01-19"),
    },
    {
        id: "6",
        name: "Robert Williams",
        email: "r.williams@email.com",
        phone: "+91 98765 43215",
        status: "new",
        source: "event",
        budgetMin: 5000000,
        budgetMax: 6000000,
        preferredLocation: "Hoboken, New Jersey",
        propertyType: "Villa",
        bedroom: 3,
        notes: "Met at real estate expo, interested in waterfront properties",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-26"),
    },
    {
        id: "7",
        name: "Jennifer Martinez",
        email: "jenn.m@design.co",
        phone: "+91 98765 43216",
        status: "lost",
        source: "referral",
        budgetMin: 4000000,
        budgetMax: 5000000,
        preferredLocation: "Williamsburg, Brooklyn",
        propertyType: "Apartment",
        bedroom: 2,
        lostReason: "bought_elsewhere",
        notes: "Found property through another agent",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-08"),
        lastContact: new Date("2024-01-15"),
    },
    {
        id: "8",
        name: "James Taylor",
        email: "james.t@finance.com",
        phone: "+91 98765 43217",
        status: "qualified",
        source: "magicbricks",
        budgetMin: 9000000,
        budgetMax: 12000000,
        preferredLocation: "Upper East Side, Manhattan",
        propertyType: "Penthouse",
        bedroom: 4,
        notes: "Investment property, looking for rental income potential",
        assignedTo: { id: "agent-1", name: "Indica Watson" },
        createdAt: new Date("2024-01-14"),
        lastContact: new Date("2024-01-23"),
    },
]